create sequence hibernate_sequence start 1 increment 1;
create table privilegeModel (id int8 not null, name varchar(255), primary key (id));
create table roleModel (id int8 not null, name varchar(255), primary key (id));
create table roles_privileges (role_id int8 not null, privilege_id int8 not null);
create table userModel (id int8 not null, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), token_expired boolean not null, primary key (id));
create table users_roles (user_id int8 not null, role_id int8 not null);
alter table roles_privileges add constraint FK5yjwxw2gvfyu76j3rgqwo685u foreign key (privilege_id) references privilegeModel;
alter table roles_privileges add constraint FK9h2vewsqh8luhfq71xokh4who foreign key (role_id) references roleModel;
alter table users_roles add constraint FKt4v0rrweyk393bdgt107vdx0x foreign key (role_id) references roleModel;
alter table users_roles add constraint FKgd3iendaoyh04b95ykqise6qh foreign key (user_id) references userModel;
create sequence hibernate_sequence start 1 increment 1;
create table privilegeModel (id int8 not null, name varchar(255), primary key (id));
create table roleModel (id int8 not null, name varchar(255), primary key (id));
create table roles_privileges (role_id int8 not null, privilege_id int8 not null);
create table userModel (id int8 not null, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), token_expired boolean not null, primary key (id));
create table users_roles (user_id int8 not null, role_id int8 not null);
alter table roles_privileges add constraint FK5yjwxw2gvfyu76j3rgqwo685u foreign key (privilege_id) references privilegeModel;
alter table roles_privileges add constraint FK9h2vewsqh8luhfq71xokh4who foreign key (role_id) references roleModel;
alter table users_roles add constraint FKt4v0rrweyk393bdgt107vdx0x foreign key (role_id) references roleModel;
alter table users_roles add constraint FKgd3iendaoyh04b95ykqise6qh foreign key (user_id) references userModel;
